packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.62.8
  "@trpc/client": ^11.0.0-rc.660
  "@trpc/react-query": ^11.0.0-rc.660
  "@trpc/server": ^11.0.0-rc.660
  ai: ^4.0.21
  eslint: ^9.17.0
  lucide-react: "^0.469.0"
  prettier: ^3.4.2
  superjson: ^2.2.2
  typescript: ^5.7.2
  zod: ^3.24.1
  "@types/node": ^20.17.7

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.2.0
  nextjs:
    next: ^15.1.2
    "@next/bundle-analyzer": ^15.1.2
    "@next/third-parties": ^15.1.2
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2
  sentry:
    "@sentry/nextjs": ^8.47.0
  supabase:
    supabase: ^2.1.1
    "@supabase/supabase-js": ^2.47.10
    "@supabase/ssr": ^0.5.2
  tailwind:
    tailwindcss: ^3.4.17
    tailwindcss-animate: ^1.0.7
  vercel:
    "@vercel/toolbar": ^0.1.30
