packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.62.3
  "@trpc/client": ^11.0.0-rc.648
  "@trpc/react-query": ^11.0.0-rc.648
  "@trpc/server": ^11.0.0-rc.648
  eslint: ^9.16.0
  prettier: ^3.4.1
  superjson: ^2.2.1
  typescript: ^5.7.2
  zod: ^3.23.8

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.2.0
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  supabase:
    "@supabase/supabase-js": ^2.46.2
    "@supabase/ssr": ^0.5.2
  tailwind:
    tailwindcss: ^3.4.15
    tailwindcss-animate: ^1.0.7
