packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.62.3
  "@trpc/client": ^11.0.0-rc.660
  "@trpc/react-query": ^11.0.0-rc.660
  "@trpc/server": ^11.0.0-rc.660
  eslint: ^9.16.0
  prettier: ^3.4.1
  superjson: ^2.2.1
  typescript: ^5.7.2
  zod: ^3.24.1
  "@types/node": ^20.17.7

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.2.0
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.2
  supabase:
    supabase: ^2.0.0
    "@supabase/supabase-js": ^2.46.2
    "@supabase/ssr": ^0.5.2
  tailwind:
    tailwindcss: ^3.4.15
    tailwindcss-animate: ^1.0.7
