packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.60.5
  "@trpc/client": ^11.0.0-rc.638
  "@trpc/react-query": ^11.0.0-rc.638
  "@trpc/server": ^11.0.0-rc.638
  eslint: ^9.15.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.2.0
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
  supabase:
    "@supabase/supabase-js": ^2.46.1
    "@supabase/ssr": ^0.5.2
  tailwind:
    tailwindcss: ^3.4.15
    tailwindcss-animate: ^1.0.7
